import test from 'node:test';import assert from 'node:assert/strict';import {createApp} from '../server.mjs';import {MEDIA_LIMITS,readLimited,identifyMedia} from '../media.mjs';import {loadConfig} from '../config.mjs';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
async function withServer(options,action){const server=createApp(options);await new Promise(r=>server.listen(0,'127.0.0.1',r));try{await action('http://127.0.0.1:'+server.address().port);}finally{server.closeAllConnections();await new Promise(r=>server.close(r));}}
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==','base64');
const wav=Buffer.alloc(46);wav.write('RIFF');wav.writeUInt32LE(38,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(8000,24);wav.writeUInt32LE(16000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(2,40);
const upload=(bytes,name)=>({method:'POST',headers:{'Content-Type':'application/octet-stream','X-File-Name':encodeURIComponent(name)},body:bytes});
const completed=text=>Response.json({status:'completed',output:[{content:[{type:'output_text',text}]}]});
test('imagen usa visión, mantiene la clave en servidor y devuelve texto revisable',async()=>{let payload;await withServer({apiKey:'secret-test',model:'text-test',visionModel:'vision-test',fetchImpl:async(url,options)=>{assert.equal(url,'https://api.openai.com/v1/responses');assert.equal(options.headers.Authorization,'Bearer secret-test');payload=JSON.parse(options.body);return completed('Un constructor es un método.\nVp = Vrms × √2');}},async base=>{const r=await fetch(base+'/api/extract/image',upload(png,'Pizarra española.png'));assert.equal(r.status,200);const data=await r.json();assert.equal(data.fileName,'Pizarra española.png');assert.equal(data.kind,'image');assert.ok(data.text.includes('Vp ='));assert.equal(payload.model,'vision-test');assert.equal(payload.store,false);assert.equal(payload.input[0].content[1].image_url,'data:image/png;base64,'+png.toString('base64'));assert.ok(!JSON.stringify(data).includes('secret-test'));assert.equal((await fetch(base+'/.env')).status,404);assert.equal((await fetch(base+'/media.mjs')).status,404);});});
test('audio envía el archivo mediante multipart con modelo de transcripción',async()=>{await withServer({apiKey:'test',model:null,visionModel:null,audioModel:'gpt-4o-mini-transcribe',fetchImpl:async(url,options)=>{assert.equal(url,'https://api.openai.com/v1/audio/transcriptions');assert.ok(options.body instanceof FormData);assert.equal(options.body.get('file').name,'clase.wav');assert.equal(options.body.get('file').size,wav.length);assert.equal(options.body.get('model'),'gpt-4o-mini-transcribe');assert.equal(options.body.get('response_format'),'json');assert.ok(!options.headers['Content-Type']);return Response.json({text:'Una clase es una estructura.'});}},async base=>{const status=await(await fetch(base+'/api/status')).json();assert.equal(status.audioConfigured,true);assert.equal(status.aiConfigured,false);assert.equal(status.imageConfigured,false);const r=await fetch(base+'/api/extract/audio',upload(wav,'clase.wav'));assert.equal(r.status,200);assert.equal((await r.json()).text,'Una clase es una estructura.');});});
test('formatos falsos, vacíos y origen externo no llaman al proveedor',async()=>{let calls=0;await withServer({apiKey:'test',model:'test',fetchImpl:async()=>{calls++;throw new Error('Unexpected');}},async base=>{assert.equal((await fetch(base+'/api/extract/image',upload(Buffer.from('<svg/>'),'foto.png'))).status,415);assert.equal((await fetch(base+'/api/extract/audio',upload(png,'audio.mp3'))).status,415);assert.equal((await fetch(base+'/api/extract/image',upload(Buffer.alloc(0),'foto.png'))).status,400);const req=upload(png,'foto.png');req.headers.Origin='https://example.invalid';assert.equal((await fetch(base+'/api/extract/image',req)).status,403);assert.equal(calls,0);});});
test('límites de tamaño se aplican antes de procesar, incluso sin Content-Length',async()=>{const req={headers:{'content-length':MEDIA_LIMITS.image+1},async *[Symbol.asyncIterator](){throw new Error('Should not read');}};await assert.rejects(readLimited(req,MEDIA_LIMITS.image),{status:413});const streamed={headers:{},async *[Symbol.asyncIterator](){yield Buffer.alloc(5);yield Buffer.alloc(6);}};await assert.rejects(readLimited(streamed,10),{status:413});assert.throws(()=>identifyMedia('image',png,'foto.svg'),{status:415});});
test('sin credenciales no se envía multimedia; errores y respuestas incompletas no filtran secretos',async()=>{await withServer({apiKey:null,model:null},async base=>{assert.equal((await fetch(base+'/api/extract/audio',upload(wav,'clase.wav'))).status,503);assert.equal((await fetch(base+'/api/extract/image',upload(png,'foto.png'))).status,503);});for(const response of [()=>Response.json({error:'secret-test'},{status:401}),()=>Response.json({status:'incomplete',output:[]}),()=>completed(''),()=>completed('x'.repeat(60001))])await withServer({apiKey:'secret-test',model:'test',fetchImpl:async()=>response()},async base=>{const r=await fetch(base+'/api/extract/image',upload(png,'foto.png'));assert.ok(r.status>=400);assert.ok(!(await r.text()).includes('secret-test'));});});
test('la configuración privada respeta variables previas y no ejecuta instrucciones',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'visualnotes-config-'));try{const file=path.join(dir,'.env');await fs.writeFile(file,'# example\nOPENAI_API_KEY="fake-key"\nOPENAI_MODEL=test-model\nPORT=4317 # local\nHOME=ignored\nOPENAI_VISION_MODEL=$(not-executed)\n');const env={OPENAI_API_KEY:'existing'};await loadConfig(file,env);assert.equal(env.OPENAI_API_KEY,'existing');assert.equal(env.OPENAI_MODEL,'test-model');assert.equal(env.PORT,'4317');assert.equal(env.HOME,undefined);assert.equal(env.OPENAI_VISION_MODEL,'$(not-executed)');}finally{await fs.unlink(path.join(dir,'.env'));await fs.rmdir(dir);}});
