import test from 'node:test';import assert from 'node:assert/strict';import {createApp} from '../server.mjs';
async function withServer(options,action){const server=createApp({provider:"openai",...options});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));try{await action('http://127.0.0.1:'+server.address().port);}finally{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}}
const text='Un constructor es un método.';const raw={title:'Objetos',concepts:[{id:'c1',label:'Constructor',sourceIds:['s1']}],relations:[],events:[],procedures:[],tables:[],formulas:[]};
const request=body=>({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
test('servidor local sirve interfaz, no expone archivos internos y funciona sin IA',async()=>{await withServer({apiKey:null,model:null},async base=>{assert.equal((await fetch(base)).status,200);assert.deepEqual(await(await fetch(base+'/api/status')).json(),{aiConfigured:false,imageConfigured:false,audioConfigured:false});assert.equal((await fetch(base+'/server.mjs')).status,404);assert.equal((await fetch(base+'/../README.md')).status,404);assert.equal((await fetch(base+'/api/analyze',request({text}))).status,503);});});
test('IA simulada envía esquema estricto y valida respuesta',async()=>{let payload;await withServer({apiKey:'test-only',model:'test-model',fetchImpl:async(url,options)=>{assert.equal(url,'https://api.openai.com/v1/responses');payload=JSON.parse(options.body);return Response.json({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify(raw)}]}]});}},async base=>{const r=await fetch(base+'/api/analyze',request({text}));assert.equal(r.status,200);assert.deepEqual(await r.json(),raw);assert.equal(payload.store,false);assert.equal(payload.text.format.strict,true);assert.equal(JSON.parse(payload.input).fragments[0].text,text);});});
test('respuestas con fuentes falsas, incompletas o rechazo no llegan a la interfaz',async()=>{for(const data of [{status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify({...raw,concepts:[{...raw.concepts[0],sourceIds:['s999']}]})}]}]},{status:'incomplete',output:[]},{status:'completed',output:[{content:[{type:'refusal',refusal:'test'}]}]}])await withServer({apiKey:'test-only',model:'test-model',fetchImpl:async()=>Response.json(data)},async base=>{assert.ok((await fetch(base+'/api/analyze',request({text}))).status>=400);});});
test('error del proveedor no filtra credenciales ni contenido',async()=>{await withServer({apiKey:'secret-test-key',model:'test',fetchImpl:async()=>Response.json({error:'secret-test-key'},{status:401})},async base=>{const r=await fetch(base+'/api/analyze',request({text}));assert.equal(r.status,502);assert.ok(!(await r.text()).includes('secret-test-key'));});});
test('origen externo y entradas inválidas se rechazan antes del proveedor',async()=>{let calls=0;await withServer({apiKey:'test-only',model:'test',fetchImpl:async()=>{calls++;throw new Error('Unexpected');}},async base=>{assert.equal((await fetch(base+'/api/analyze',{...request({text}),headers:{'Content-Type':'application/json',Origin:'https://example.invalid'}})).status,403);assert.equal((await fetch(base+'/api/analyze',request({text:''}))).status,400);assert.equal((await fetch(base+'/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:'{'})).status,400);assert.equal(calls,0);});});
